src/core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include('users.urls', namespace='users')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]


src/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(next_page='weather:index'), name='logout'),
]

src/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'
urlpatterns = [
    path('', views.index, name='index'),
    path('weather/', views.get_city_weather, name='weather_data'),
    path('weather/save/', views.save_to_db_location, name='weather_data_save'),
    path('weather/<int:pk>/', views.delete_location, name='delete_data'),
    # path('', views.Index.as_view(), name='index'),
    # path('weather/', views.GetCityWeather.as_view(), name='weather_data'),
    # path('weather/<int:pk>/', views.DeleteLocation.as_view(), name='delete_data'),


]

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'weather/css/bootstrap.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <!-- Navbar content -->

<div>
   <nav class="navbar navbar-expand-lg navbar-light ">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar scroll</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">

        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'weather:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Link
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Поиск</a>
            </li>
          </ul>
          {% if user.is_authenticated %}

          <form class="d-flex" action="{% url 'weather:weather_data' %}">
            <input class="form-control me-2" type="search" placeholder="Введите город" required name="city" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Найти</button>
          </form>
            <div class="navbar-brand">Поиск по локации</div>
          <div class="nav-link active"  ><a class="navbar-brand" href="{% url 'users:profile' %}">{{ user }}</a></div>
          <a type="button" class="btn btn-primary btn-sm float-right"  href="{% url 'users:logout' %}">Выйти</a>
            {% endif %}

        </div>

      </div>

    </nav>

  </div>

</nav>
</body>
<div>
{% block content %}
{% endblock %}
  </div>
</html>