src/core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include('users.urls', namespace='users')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]


src/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(next_page='weather:index'), name='logout'),
]

src/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'
urlpatterns = [
    path('', views.index, name='index'),
    path('weather/', views.get_city_weather, name='weather_data'),
    path('weather/save/', views.save_to_db_location, name='weather_data_save'),
    path('weather/<int:pk>/', views.delete_location, name='delete_data'),
    # path('', views.Index.as_view(), name='index'),
    # path('weather/', views.GetCityWeather.as_view(), name='weather_data'),
    # path('weather/<int:pk>/', views.DeleteLocation.as_view(), name='delete_data'),


]

src/weather/models.py
from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.
class Locations(models.Model):
    name = models.CharField(max_length=250, verbose_name='Название локации', db_index=True)
    userid = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=None, null=False,
                               related_name='users')
    latitude = models.DecimalField(max_digits=20, decimal_places=10, verbose_name='Широта локации')
    longitude = models.DecimalField(max_digits=20, decimal_places=10, verbose_name='Долгота локации')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Локация'
        verbose_name_plural = 'Локации'
        ordering = ('name',)
        indexes = [
            models.Index(fields=['name'])
        ]

src/weather/views.py
from django.shortcuts import render, redirect

from .dependencies.dependencies import services
from .services.cached_service import CacheService
import logging

logger = logging.getLogger('web')


def index(request):
    if request.user.is_authenticated:
        print(f" User {request.user}")
        get_cities = services.weather_db_service.get_all_locations(request.user)
        return render(request, "weather/index_home.html", {"weather_data": get_cities})
    return render(request, "weather/index_home.html")


def get_city_weather(request):
    if request.method == "GET":
        city = request.GET.get('city')
        cached_data = CacheService().get_cached(city)

        if cached_data:
            logger.debug(f"Получены данные из кеша: {cached_data}")
            context = services.weather_api_service.get_mixin_context({}, cached_data)
            return render(request, 'weather/weather.html', {"weather": context})
        else:
            get_city_from_api = services.weather_api_service.get_city_weather(city)
            logger.debug(f"Данные из API: {get_city_from_api}")
            cached = CacheService().create_cache(city=city, data=get_city_from_api)
            context = services.weather_api_service.get_mixin_context({}, cached)
            return render(request, 'weather/weather.html', {"weather": context})


def save_to_db_location(request):
    if request.method == "POST":
        save = services.weather_db_service.save_location(request.user, **request.POST)
        return redirect("weather:index")


def delete_location(request, pk):
    if request.method == "POST":
        user = request.user
        logger.debug(f"Запрос на удаление pk={pk} пользователя user={user}")
        services.weather_db_service.delete_location(pk)

        return redirect('weather:index')
    return redirect('weather:index')

# class Index(ListView, WeatherAPIService):  # IndexContext
#     template_name = 'weather/index_home.html'
#     title_page = 'Главная страница'
#     context_object_name = 'location_data'
#
#     def get_queryset(self):
#         if self.request.user.is_authenticated:
#             # Удаление из базы если нет в кеше
#             cached_cities = cache.get('cached_cities', [])
#             cities_in_db = Locations.objects.values_list('name', flat=True)
#             cities_to_delete = [city for city in cities_in_db if city not in cached_cities]
#             Locations.objects.filter(name__in=cities_to_delete).delete()
#
#             return Locations.objects.filter(userid=self.request.user)
#         else:
#             return Locations.objects.none()
#
#     def get_context_data(self, **kwargs):
#         """Добавляем данные из кеша в контекст"""
#         context = super().get_context_data(**kwargs)
#
#         cached_cities = cache.get('cached_cities', [])
#         cached_weather_data = [cache.get(f'cached_city_{city}') for city in cached_cities]
#         context_weather = self.index_queryset(cached_weather_data)
#         context['weather_data'] = context_weather
#
#         return context
#
#
# class GetCityWeather(TemplateView, WeatherAPIService):  # GetContextAPI
#     template_name = 'weather/weather.html'
#     model = Locations
#
#     def get_context_data(self, **kwargs):
#         """Формируем контекст"""
#         context = super().get_context_data(**kwargs)
#         city = self.request.GET.get('city')
#         data = self.get_city_weather(city)
#         cached = CacheService().create_cache(city=city, data=data)
#         context['city'] = self.request.GET.get('city')
#         return self.get_mixin_context(context, cached)
#
#     def post(self, request, *args, **kwargs):
#         """Добавление записи в БД"""
#         data_weather = {
#             "city": request.POST.get('name'),
#             "latitude": request.POST.get('latitude'),
#             "longitude": request.POST.get('longitude'),
#             "user": request.user
#
#         }
#         save_location = WeatherDatabaseService(LocationsRepository()).save_location(**data_weather)
#
#         return redirect('weather:index')
#
#
# class DeleteLocation(DeleteView):
#     model = Locations
#     success_url = reverse_lazy('weather:index')
#
#     def get_object(self, queryset=None):
#         get_pk = self.kwargs['pk']
#         user = self.request.user
#         # location = Locations.objects.get(id=get_pk, userid=self.request.user)
#         location = WeatherDatabaseService(LocationsRepository()).get_location(id=get_pk, userid=user)
#         # Очистка кеша
#         # delete_cached(location.name)
#         # get_cached(location)
#         # if location in cached_cities:
#         #     cached_cities.remove(location)
#         #     cache.set('cached_cities', cached_cities)
#
#         return location
#
#     def delete(self, request, *args, **kwargs):
#         obj = self.get_object()
#         self.object = obj
#         cached_cities = cache.get('cached_cities', [])
#         if self.object.name in cached_cities:
#             CacheService().delete_cached(self.object.name)
#         self.object.delete()
#         return redirect(self.success_url)

src/weather/templates/weather/index_home.html
{% extends 'base.html' %}

{% block content %}

<div>

    {% if user.is_authenticated %}
    <div class="container">
            <h3 class="mb-4 pb-2 fw-normal">Недавно просмотренные</h3>
          <div>
            {% for item in weather_data %}
              <div>
<!--                <section class="vh-100">-->
              <div class="container py-4 h-100">
<!--                <div class="row d-flex justify-content-center align-items-center h-100">-->
                  <div class="col-md-8 col-lg-6 col-xl-4">
                    <div class="card shadow-0 border">
                      <div class="card-body p-4">

                          <h4 class="mb-1 sfw-normal">{{ item.name }}</h4>



                        <div class="d-flex flex-row align-items-center">
                          <p class="mb-0 me-4">Scattered Clouds</p>
                          <i class="fas fa-cloud fa-3x" style="color: #eee;"></i>
                        </div>
                        <p>Lon: <strong>{{ item.longitude }}</strong>, lat: <strong>{{ item.latitude }}</strong></p>
                          <p>Max temp: <strong>{{ item.temp_max }}</strong></p>
                          <p>Max min: <strong>{{ item.temp_min }}</strong></p>
                          <p>Current temp: <strong>{{ item.current_temp }}</strong></p>
                          <p>Feels like: <strong>{{ item.feels_like }}</strong> </p>

                      </div>

                        <div>
                            <form method="post" action="{% url 'weather:delete_data' item.pk  %}">
                                 {% csrf_token %}
                             <button type="submit" class="btn btn-outline-danger" >Удалить</button>
                            </form>

                        </div>

                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
            </div>


        </div>




        </div>
    {% else %}
    <div style="text-align: center;">
        <h1 >Чтобы начать войдите в аккаунт или зарегестрируйтесь</h1>
        <a type="button" class="btn btn-primary btn-sm" href="{% url 'users:login' %}">Войти</a> | <a type="button" class="btn btn-secondary btn-sm"   href="{% url 'users:register' %}">Регистрация</a>
    </div>
        {% endif %}
</div>
{% endblock %}

src/weather/templates/weather/weather.html
{% extends 'base.html' %}

{% block content %}
<div>
<!--    <section class="vh-100">-->
  <div class="container py-5 h-100">

    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-8 col-lg-6 col-xl-4">

        <h3 class="mb-4 pb-2 fw-normal">Check the weather forecast</h3>

        <div class="card shadow-0 border">
          <div class="card-body p-4">

            <h4 class="mb-1 sfw-normal">{{ weather.city }}, US</h4>
            <p class="mb-2">Current temperature: <strong>{{ weather.current_temp }}°C</strong></p>
            <p>Feels like: <strong>{{ weather.feels_like }}°C</strong></p>
            <p>Max: <strong>{{ weather.temp_max }}°C</strong>, Min: <strong>{{ weather.temp_min }}°C</strong></p>

            <div class="d-flex flex-row align-items-center">
              <p class="mb-0 me-4">Scattered Clouds</p>
              <i class="fas fa-cloud fa-3x" style="color: #eee;"></i>
            </div>
            <p>Lon: <strong>{{ weather.get_lon }}</strong>, lat: <strong>{{ weather.get_lat }}</strong></p>
          </div>
         <div>
            <form method="post" action="{% url 'weather:weather_data_save' %}">
             {% csrf_token %}
            <input type="hidden" name="name" value="{{ weather.city }}">
            <input type="hidden" name="latitude" value="{{ weather.get_lat }}">
            <input type="hidden" name="longitude" value="{{ weather.get_lon }}">
             <button type="submit" class="btn btn-outline-success">Добавить</button>
            </form>
        </div>


      </div>
    </div>

  </div>
</section>
</div>
</div>


{% endblock %}